{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-management.fullname" . }}-database
  labels:
    app: {{ include "task-management.name" . }}-database
    {{- include "task-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "task-management.name" . }}-database
  template:
    metadata:
      labels:
        app: {{ include "task-management.name" . }}-database
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.database.service.port }}
              protocol: TCP
          env:
            {{- toYaml .Values.database.env | nindent 12 }}
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
          {{- if .Values.database.persistence.enabled }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          {{- end }}
      {{- if .Values.database.persistence.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "task-management.fullname" . }}-database-pvc
      {{- end }}
{{- end }}
